name: Linting code

on: [push, pull_request]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      
      # Check for linter compliance
      - name: Lint with Ruff
        uses: astral-sh/ruff-action@v3

      # Check for formatter compliance
      - name: Check formatting with Ruff
        if: always()
        uses: astral-sh/ruff-action@v3
        with:
          args: 'format --check'
